# Generated by Django 5.0.1 on 2024-01-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_klient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='aktualna_znizka',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='klient',
            name='liczba_rezerwacji',
            field=models.IntegerField(default=0),
        ),
    ]
