# Generated by Django 4.2.8 on 2023-12-20 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('rok_produkcji', models.IntegerField()),
                ('dostepny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField()),
                ('data_zwrotu', models.DateField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezerwacje.klient')),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezerwacje.samochod')),
            ],
        ),
    ]
