# Generated by Django 4.2.8 on 2023-12-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0002_rezerwacja_cena_rezerwacji_samochod_cena_wynajmu'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='pojemnosc_silnika',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='samochod',
            name='rodzaj_paliwa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
