# Generated by Django 4.2.8 on 2023-12-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinansoweStatystyki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField()),
                ('przychody', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('koszty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
