# Generated by Django 5.0.1 on 2024-01-15 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0001_initial'),
        ('Client', '0002_alter_klient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.klient')),
            ],
        ),
    ]
