# Generated by Django 5.0.1 on 2024-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('rok_produkcji', models.IntegerField()),
                ('dostepny', models.BooleanField(default=True)),
                ('cena_wynajmu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rodzaj_paliwa', models.CharField(blank=True, max_length=20, null=True)),
                ('pojemnosc_silnika', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
